// Generated by scripts/generate-assets.mjs — do not edit by hand.
/* eslint-disable */

/** Bundled placeholder images for the demo wardrobe, keyed by slug. */
export const SEED_IMAGES: Record<string, { cutout: number; thumb: number; original?: number }> = {
  'camel-wool-coat': {
    cutout: require('../../../assets/seed/camel-wool-coat.webp'),
    thumb: require('../../../assets/seed/thumbs/camel-wool-coat.webp'),
    original: require('../../../assets/seed/originals/camel-wool-coat.jpg'),
  },
  'stone-trench': {
    cutout: require('../../../assets/seed/stone-trench.webp'),
    thumb: require('../../../assets/seed/thumbs/stone-trench.webp'),
    original: require('../../../assets/seed/originals/stone-trench.jpg'),
  },
  'navy-blazer': {
    cutout: require('../../../assets/seed/navy-blazer.webp'),
    thumb: require('../../../assets/seed/thumbs/navy-blazer.webp'),
    original: require('../../../assets/seed/originals/navy-blazer.jpg'),
  },
  'olive-utility-jacket': {
    cutout: require('../../../assets/seed/olive-utility-jacket.webp'),
    thumb: require('../../../assets/seed/thumbs/olive-utility-jacket.webp'),
    original: require('../../../assets/seed/originals/olive-utility-jacket.jpg'),
  },
  'denim-jacket': {
    cutout: require('../../../assets/seed/denim-jacket.webp'),
    thumb: require('../../../assets/seed/thumbs/denim-jacket.webp'),
    original: require('../../../assets/seed/originals/denim-jacket.jpg'),
  },
  'ecru-linen-shirt': {
    cutout: require('../../../assets/seed/ecru-linen-shirt.webp'),
    thumb: require('../../../assets/seed/thumbs/ecru-linen-shirt.webp'),
    original: require('../../../assets/seed/originals/ecru-linen-shirt.jpg'),
  },
  'sky-oxford-shirt': {
    cutout: require('../../../assets/seed/sky-oxford-shirt.webp'),
    thumb: require('../../../assets/seed/thumbs/sky-oxford-shirt.webp'),
    original: require('../../../assets/seed/originals/sky-oxford-shirt.jpg'),
  },
  'blush-silk-blouse': {
    cutout: require('../../../assets/seed/blush-silk-blouse.webp'),
    thumb: require('../../../assets/seed/thumbs/blush-silk-blouse.webp'),
    original: require('../../../assets/seed/originals/blush-silk-blouse.jpg'),
  },
  'rust-slip-dress': {
    cutout: require('../../../assets/seed/rust-slip-dress.webp'),
    thumb: require('../../../assets/seed/thumbs/rust-slip-dress.webp'),
    original: require('../../../assets/seed/originals/rust-slip-dress.jpg'),
  },
  'black-midi-dress': {
    cutout: require('../../../assets/seed/black-midi-dress.webp'),
    thumb: require('../../../assets/seed/thumbs/black-midi-dress.webp'),
    original: require('../../../assets/seed/originals/black-midi-dress.jpg'),
  },
  'olive-midi-skirt': {
    cutout: require('../../../assets/seed/olive-midi-skirt.webp'),
    thumb: require('../../../assets/seed/thumbs/olive-midi-skirt.webp'),
    original: require('../../../assets/seed/originals/olive-midi-skirt.jpg'),
  },
  'cream-cable-knit': {
    cutout: require('../../../assets/seed/cream-cable-knit.webp'),
    thumb: require('../../../assets/seed/thumbs/cream-cable-knit.webp'),
    original: require('../../../assets/seed/originals/cream-cable-knit.jpg'),
  },
  'charcoal-merino': {
    cutout: require('../../../assets/seed/charcoal-merino.webp'),
    thumb: require('../../../assets/seed/thumbs/charcoal-merino.webp'),
    original: require('../../../assets/seed/originals/charcoal-merino.jpg'),
  },
  'burgundy-cardigan': {
    cutout: require('../../../assets/seed/burgundy-cardigan.webp'),
    thumb: require('../../../assets/seed/thumbs/burgundy-cardigan.webp'),
    original: require('../../../assets/seed/originals/burgundy-cardigan.jpg'),
  },
  'mustard-crewneck': {
    cutout: require('../../../assets/seed/mustard-crewneck.webp'),
    thumb: require('../../../assets/seed/thumbs/mustard-crewneck.webp'),
    original: require('../../../assets/seed/originals/mustard-crewneck.jpg'),
  },
  'white-tee': {
    cutout: require('../../../assets/seed/white-tee.webp'),
    thumb: require('../../../assets/seed/thumbs/white-tee.webp'),
    original: require('../../../assets/seed/originals/white-tee.jpg'),
  },
  'black-tee': {
    cutout: require('../../../assets/seed/black-tee.webp'),
    thumb: require('../../../assets/seed/thumbs/black-tee.webp'),
    original: require('../../../assets/seed/originals/black-tee.jpg'),
  },
  'indigo-jeans': {
    cutout: require('../../../assets/seed/indigo-jeans.webp'),
    thumb: require('../../../assets/seed/thumbs/indigo-jeans.webp'),
    original: require('../../../assets/seed/originals/indigo-jeans.jpg'),
  },
  'stone-chinos': {
    cutout: require('../../../assets/seed/stone-chinos.webp'),
    thumb: require('../../../assets/seed/thumbs/stone-chinos.webp'),
    original: require('../../../assets/seed/originals/stone-chinos.jpg'),
  },
  'black-trousers': {
    cutout: require('../../../assets/seed/black-trousers.webp'),
    thumb: require('../../../assets/seed/thumbs/black-trousers.webp'),
    original: require('../../../assets/seed/originals/black-trousers.jpg'),
  },
  'charcoal-merino-socks': {
    cutout: require('../../../assets/seed/charcoal-merino-socks.webp'),
    thumb: require('../../../assets/seed/thumbs/charcoal-merino-socks.webp'),
    original: require('../../../assets/seed/originals/charcoal-merino-socks.jpg'),
  },
  'mustard-socks': {
    cutout: require('../../../assets/seed/mustard-socks.webp'),
    thumb: require('../../../assets/seed/thumbs/mustard-socks.webp'),
    original: require('../../../assets/seed/originals/mustard-socks.jpg'),
  },
  'black-leggings': {
    cutout: require('../../../assets/seed/black-leggings.webp'),
    thumb: require('../../../assets/seed/thumbs/black-leggings.webp'),
    original: require('../../../assets/seed/originals/black-leggings.jpg'),
  },
  'forest-running-top': {
    cutout: require('../../../assets/seed/forest-running-top.webp'),
    thumb: require('../../../assets/seed/thumbs/forest-running-top.webp'),
    original: require('../../../assets/seed/originals/forest-running-top.jpg'),
  },
  'white-sneakers': {
    cutout: require('../../../assets/seed/white-sneakers.webp'),
    thumb: require('../../../assets/seed/thumbs/white-sneakers.webp'),
    original: require('../../../assets/seed/originals/white-sneakers.jpg'),
  },
  'chelsea-boots': {
    cutout: require('../../../assets/seed/chelsea-boots.webp'),
    thumb: require('../../../assets/seed/thumbs/chelsea-boots.webp'),
    original: require('../../../assets/seed/originals/chelsea-boots.jpg'),
  },
  'black-loafers': {
    cutout: require('../../../assets/seed/black-loafers.webp'),
    thumb: require('../../../assets/seed/thumbs/black-loafers.webp'),
    original: require('../../../assets/seed/originals/black-loafers.jpg'),
  },
  'sage-trainers': {
    cutout: require('../../../assets/seed/sage-trainers.webp'),
    thumb: require('../../../assets/seed/thumbs/sage-trainers.webp'),
    original: require('../../../assets/seed/originals/sage-trainers.jpg'),
  },
  'camel-tote': {
    cutout: require('../../../assets/seed/camel-tote.webp'),
    thumb: require('../../../assets/seed/thumbs/camel-tote.webp'),
    original: require('../../../assets/seed/originals/camel-tote.jpg'),
  },
  'burgundy-crossbody': {
    cutout: require('../../../assets/seed/burgundy-crossbody.webp'),
    thumb: require('../../../assets/seed/thumbs/burgundy-crossbody.webp'),
    original: require('../../../assets/seed/originals/burgundy-crossbody.jpg'),
  },
  'leather-belt': {
    cutout: require('../../../assets/seed/leather-belt.webp'),
    thumb: require('../../../assets/seed/thumbs/leather-belt.webp'),
    original: require('../../../assets/seed/originals/leather-belt.jpg'),
  },
  'rust-scarf': {
    cutout: require('../../../assets/seed/rust-scarf.webp'),
    thumb: require('../../../assets/seed/thumbs/rust-scarf.webp'),
    original: require('../../../assets/seed/originals/rust-scarf.jpg'),
  },
  'olive-bucket-hat': {
    cutout: require('../../../assets/seed/olive-bucket-hat.webp'),
    thumb: require('../../../assets/seed/thumbs/olive-bucket-hat.webp'),
    original: require('../../../assets/seed/originals/olive-bucket-hat.jpg'),
  },
  'gold-pendant': {
    cutout: require('../../../assets/seed/gold-pendant.webp'),
    thumb: require('../../../assets/seed/thumbs/gold-pendant.webp'),
    original: require('../../../assets/seed/originals/gold-pendant.jpg'),
  },
  'charcoal-overcoat': {
    cutout: require('../../../assets/seed/charcoal-overcoat.webp'),
    thumb: require('../../../assets/seed/thumbs/charcoal-overcoat.webp'),
    original: require('../../../assets/seed/originals/charcoal-overcoat.jpg'),
  },
  'black-puffer': {
    cutout: require('../../../assets/seed/black-puffer.webp'),
    thumb: require('../../../assets/seed/thumbs/black-puffer.webp'),
    original: require('../../../assets/seed/originals/black-puffer.jpg'),
  },
  'wish-wide-leg-trousers': {
    cutout: require('../../../assets/seed/wish-wide-leg-trousers.webp'),
    thumb: require('../../../assets/seed/thumbs/wish-wide-leg-trousers.webp'),
  },
  'wish-cream-trench': {
    cutout: require('../../../assets/seed/wish-cream-trench.webp'),
    thumb: require('../../../assets/seed/thumbs/wish-cream-trench.webp'),
  },
  'wish-silk-scarf': {
    cutout: require('../../../assets/seed/wish-silk-scarf.webp'),
    thumb: require('../../../assets/seed/thumbs/wish-silk-scarf.webp'),
  },
};
