// Generated by scripts/generate-assets.mjs — do not edit by hand.
/* eslint-disable */

/** Bundled placeholder cutouts for the demo wardrobe, keyed by slug. */
export const SEED_IMAGES: Record<string, { cutout: number; thumb: number }> = {
  'camel-wool-coat': {
    cutout: require('../../../assets/seed/camel-wool-coat.webp'),
    thumb: require('../../../assets/seed/thumbs/camel-wool-coat.webp'),
  },
  'stone-trench': {
    cutout: require('../../../assets/seed/stone-trench.webp'),
    thumb: require('../../../assets/seed/thumbs/stone-trench.webp'),
  },
  'navy-blazer': {
    cutout: require('../../../assets/seed/navy-blazer.webp'),
    thumb: require('../../../assets/seed/thumbs/navy-blazer.webp'),
  },
  'olive-utility-jacket': {
    cutout: require('../../../assets/seed/olive-utility-jacket.webp'),
    thumb: require('../../../assets/seed/thumbs/olive-utility-jacket.webp'),
  },
  'denim-jacket': {
    cutout: require('../../../assets/seed/denim-jacket.webp'),
    thumb: require('../../../assets/seed/thumbs/denim-jacket.webp'),
  },
  'ecru-linen-shirt': {
    cutout: require('../../../assets/seed/ecru-linen-shirt.webp'),
    thumb: require('../../../assets/seed/thumbs/ecru-linen-shirt.webp'),
  },
  'sky-oxford-shirt': {
    cutout: require('../../../assets/seed/sky-oxford-shirt.webp'),
    thumb: require('../../../assets/seed/thumbs/sky-oxford-shirt.webp'),
  },
  'blush-silk-blouse': {
    cutout: require('../../../assets/seed/blush-silk-blouse.webp'),
    thumb: require('../../../assets/seed/thumbs/blush-silk-blouse.webp'),
  },
  'rust-slip-dress': {
    cutout: require('../../../assets/seed/rust-slip-dress.webp'),
    thumb: require('../../../assets/seed/thumbs/rust-slip-dress.webp'),
  },
  'black-midi-dress': {
    cutout: require('../../../assets/seed/black-midi-dress.webp'),
    thumb: require('../../../assets/seed/thumbs/black-midi-dress.webp'),
  },
  'olive-midi-skirt': {
    cutout: require('../../../assets/seed/olive-midi-skirt.webp'),
    thumb: require('../../../assets/seed/thumbs/olive-midi-skirt.webp'),
  },
  'cream-cable-knit': {
    cutout: require('../../../assets/seed/cream-cable-knit.webp'),
    thumb: require('../../../assets/seed/thumbs/cream-cable-knit.webp'),
  },
  'charcoal-merino': {
    cutout: require('../../../assets/seed/charcoal-merino.webp'),
    thumb: require('../../../assets/seed/thumbs/charcoal-merino.webp'),
  },
  'burgundy-cardigan': {
    cutout: require('../../../assets/seed/burgundy-cardigan.webp'),
    thumb: require('../../../assets/seed/thumbs/burgundy-cardigan.webp'),
  },
  'mustard-crewneck': {
    cutout: require('../../../assets/seed/mustard-crewneck.webp'),
    thumb: require('../../../assets/seed/thumbs/mustard-crewneck.webp'),
  },
  'white-tee': {
    cutout: require('../../../assets/seed/white-tee.webp'),
    thumb: require('../../../assets/seed/thumbs/white-tee.webp'),
  },
  'black-tee': {
    cutout: require('../../../assets/seed/black-tee.webp'),
    thumb: require('../../../assets/seed/thumbs/black-tee.webp'),
  },
  'indigo-jeans': {
    cutout: require('../../../assets/seed/indigo-jeans.webp'),
    thumb: require('../../../assets/seed/thumbs/indigo-jeans.webp'),
  },
  'stone-chinos': {
    cutout: require('../../../assets/seed/stone-chinos.webp'),
    thumb: require('../../../assets/seed/thumbs/stone-chinos.webp'),
  },
  'black-trousers': {
    cutout: require('../../../assets/seed/black-trousers.webp'),
    thumb: require('../../../assets/seed/thumbs/black-trousers.webp'),
  },
  'charcoal-merino-socks': {
    cutout: require('../../../assets/seed/charcoal-merino-socks.webp'),
    thumb: require('../../../assets/seed/thumbs/charcoal-merino-socks.webp'),
  },
  'mustard-socks': {
    cutout: require('../../../assets/seed/mustard-socks.webp'),
    thumb: require('../../../assets/seed/thumbs/mustard-socks.webp'),
  },
  'black-leggings': {
    cutout: require('../../../assets/seed/black-leggings.webp'),
    thumb: require('../../../assets/seed/thumbs/black-leggings.webp'),
  },
  'forest-running-top': {
    cutout: require('../../../assets/seed/forest-running-top.webp'),
    thumb: require('../../../assets/seed/thumbs/forest-running-top.webp'),
  },
  'white-sneakers': {
    cutout: require('../../../assets/seed/white-sneakers.webp'),
    thumb: require('../../../assets/seed/thumbs/white-sneakers.webp'),
  },
  'chelsea-boots': {
    cutout: require('../../../assets/seed/chelsea-boots.webp'),
    thumb: require('../../../assets/seed/thumbs/chelsea-boots.webp'),
  },
  'black-loafers': {
    cutout: require('../../../assets/seed/black-loafers.webp'),
    thumb: require('../../../assets/seed/thumbs/black-loafers.webp'),
  },
  'sage-trainers': {
    cutout: require('../../../assets/seed/sage-trainers.webp'),
    thumb: require('../../../assets/seed/thumbs/sage-trainers.webp'),
  },
  'camel-tote': {
    cutout: require('../../../assets/seed/camel-tote.webp'),
    thumb: require('../../../assets/seed/thumbs/camel-tote.webp'),
  },
  'burgundy-crossbody': {
    cutout: require('../../../assets/seed/burgundy-crossbody.webp'),
    thumb: require('../../../assets/seed/thumbs/burgundy-crossbody.webp'),
  },
  'leather-belt': {
    cutout: require('../../../assets/seed/leather-belt.webp'),
    thumb: require('../../../assets/seed/thumbs/leather-belt.webp'),
  },
  'rust-scarf': {
    cutout: require('../../../assets/seed/rust-scarf.webp'),
    thumb: require('../../../assets/seed/thumbs/rust-scarf.webp'),
  },
  'olive-bucket-hat': {
    cutout: require('../../../assets/seed/olive-bucket-hat.webp'),
    thumb: require('../../../assets/seed/thumbs/olive-bucket-hat.webp'),
  },
  'gold-pendant': {
    cutout: require('../../../assets/seed/gold-pendant.webp'),
    thumb: require('../../../assets/seed/thumbs/gold-pendant.webp'),
  },
  'charcoal-overcoat': {
    cutout: require('../../../assets/seed/charcoal-overcoat.webp'),
    thumb: require('../../../assets/seed/thumbs/charcoal-overcoat.webp'),
  },
  'black-puffer': {
    cutout: require('../../../assets/seed/black-puffer.webp'),
    thumb: require('../../../assets/seed/thumbs/black-puffer.webp'),
  },
  'wish-wide-leg-trousers': {
    cutout: require('../../../assets/seed/wish-wide-leg-trousers.webp'),
    thumb: require('../../../assets/seed/thumbs/wish-wide-leg-trousers.webp'),
  },
  'wish-cream-trench': {
    cutout: require('../../../assets/seed/wish-cream-trench.webp'),
    thumb: require('../../../assets/seed/thumbs/wish-cream-trench.webp'),
  },
  'wish-silk-scarf': {
    cutout: require('../../../assets/seed/wish-silk-scarf.webp'),
    thumb: require('../../../assets/seed/thumbs/wish-silk-scarf.webp'),
  },
};
